
import { Theme } from './types';

export const THEMES: Record<string, Theme> = {
  dark: {
    id: 'dark',
    name: 'Dark (Default)',
    type: 'dark',
    monacoTheme: 'vs-dark',
    colors: {
      bgApp: 'bg-gray-900',
      bgPanel: 'bg-gray-800',
      bgHeader: 'bg-gray-900',
      textMain: 'text-gray-200',
      textMuted: 'text-gray-400',
      border: 'border-gray-700',
      buttonPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white',
      buttonSecondary: 'bg-gray-800 hover:bg-gray-700',
      buttonSecondaryText: 'text-gray-300',
      scrollTrack: 'bg-gray-900',
      scrollThumb: 'bg-gray-700',
      scrollThumbHover: 'bg-gray-600',
    },
    syntax: {
      variable: 'text-blue-300',
      value: 'text-green-400',
      type: 'text-gray-500',
      address: 'text-purple-400',
      pointer: 'text-purple-400',
      highlight: 'bg-yellow-900/50',
      headerIcon: 'text-blue-500',
    }
  },
  light: {
    id: 'light',
    name: 'Light',
    type: 'light',
    monacoTheme: 'light',
    colors: {
      bgApp: 'bg-gray-100',
      bgPanel: 'bg-white',
      bgHeader: 'bg-white',
      textMain: 'text-gray-800',
      textMuted: 'text-gray-500',
      border: 'border-gray-200',
      buttonPrimary: 'bg-blue-600 hover:bg-blue-500 text-white',
      buttonSecondary: 'bg-gray-100 hover:bg-gray-200',
      buttonSecondaryText: 'text-gray-700',
      scrollTrack: 'bg-gray-100',
      scrollThumb: 'bg-gray-300',
      scrollThumbHover: 'bg-gray-400',
    },
    syntax: {
      variable: 'text-blue-700',
      value: 'text-green-600',
      type: 'text-gray-500',
      address: 'text-purple-600',
      pointer: 'text-purple-600',
      highlight: 'bg-yellow-100',
      headerIcon: 'text-blue-600',
    }
  },
  warm: {
    id: 'warm',
    name: 'Warm',
    type: 'dark',
    monacoTheme: 'vs-dark',
    colors: {
      bgApp: 'bg-stone-900',
      bgPanel: 'bg-stone-800',
      bgHeader: 'bg-stone-900',
      textMain: 'text-stone-200',
      textMuted: 'text-stone-400',
      border: 'border-stone-700',
      buttonPrimary: 'bg-orange-700 hover:bg-orange-600 text-white',
      buttonSecondary: 'bg-stone-800 hover:bg-stone-700',
      buttonSecondaryText: 'text-stone-300',
      scrollTrack: 'bg-stone-900',
      scrollThumb: 'bg-stone-700',
      scrollThumbHover: 'bg-stone-600',
    },
    syntax: {
      variable: 'text-orange-300',
      value: 'text-yellow-400',
      type: 'text-stone-500',
      address: 'text-red-400',
      pointer: 'text-red-400',
      highlight: 'bg-orange-900/40',
      headerIcon: 'text-orange-500',
    }
  },
  cool: {
    id: 'cool',
    name: 'Cool',
    type: 'dark',
    monacoTheme: 'vs-dark',
    colors: {
      bgApp: 'bg-slate-900',
      bgPanel: 'bg-slate-800',
      bgHeader: 'bg-slate-900',
      textMain: 'text-slate-200',
      textMuted: 'text-slate-400',
      border: 'border-slate-700',
      buttonPrimary: 'bg-cyan-700 hover:bg-cyan-600 text-white',
      buttonSecondary: 'bg-slate-800 hover:bg-slate-700',
      buttonSecondaryText: 'text-slate-300',
      scrollTrack: 'bg-slate-900',
      scrollThumb: 'bg-slate-700',
      scrollThumbHover: 'bg-slate-600',
    },
    syntax: {
      variable: 'text-cyan-300',
      value: 'text-emerald-400',
      type: 'text-slate-500',
      address: 'text-blue-400',
      pointer: 'text-blue-400',
      highlight: 'bg-cyan-900/40',
      headerIcon: 'text-cyan-500',
    }
  },
  neutral: {
    id: 'neutral',
    name: 'Neutral',
    type: 'dark',
    monacoTheme: 'vs-dark',
    colors: {
      bgApp: 'bg-neutral-900',
      bgPanel: 'bg-neutral-800',
      bgHeader: 'bg-neutral-900',
      textMain: 'text-neutral-200',
      textMuted: 'text-neutral-400',
      border: 'border-neutral-700',
      buttonPrimary: 'bg-neutral-700 hover:bg-neutral-600 text-white',
      buttonSecondary: 'bg-neutral-800 hover:bg-neutral-700',
      buttonSecondaryText: 'text-neutral-300',
      scrollTrack: 'bg-neutral-900',
      scrollThumb: 'bg-neutral-700',
      scrollThumbHover: 'bg-neutral-600',
    },
    syntax: {
      variable: 'text-neutral-300',
      value: 'text-neutral-400',
      type: 'text-neutral-500',
      address: 'text-neutral-500',
      pointer: 'text-neutral-500',
      highlight: 'bg-neutral-700',
      headerIcon: 'text-neutral-400',
    }
  }
};
